/*
    This file was initially machine-generated by recycle/GENERATE.js, using
    eSocial's EnvioLoteEventos-v1_1_1.xsd schema, and includes corresponding
    io-ts types.

    EDIT WITH CARE.
*/
import * as t from 'io-ts'

// TODO: should we enforce a stricter type here?
/// Define os dados de um arquivo do eSocial (evento).
export const TArquivoEsocial = t.array(t.object)

/// Define a identificação do transmissor.
export const TIdeTransmissor = t.type({
    tpInsc: t.union([
        t.literal(1),
        t.literal(2)
    ]),
    /// Número de Inscrição
    nrInsc: t.string
})

/// Define a identificação do empregador.
export const TIdeEmpregador = t.type({
    tpInsc: t.union([
        t.literal(1),
        t.literal(2)
    ]),
    /// Número de Inscrição
    nrInsc: t.string
})

/// Elemento raiz do eSocial.
export const eSocial = t.type({
    /// Representa um lote de eventos.
    envioLoteEventos: t.type({
        /// Identificação do empregador.
        ideEmpregador: TIdeEmpregador,
        /// Identificação do transmissor.
        ideTransmissor: TIdeTransmissor,
        /// Contém a relação de eventos que compõe o lote.
        eventos: t.type({
            evento: TArquivoEsocial
        })
    })
})

export type eSocial = t.TypeOf<typeof eSocial>
