import * as t from 'io-ts'
import { CostCenterInfo } from './schema/CostCenter'
import { ItemInfo } from './schema/Item'
import { SellerInfo } from './schema/Seller'
import { StockLevelInfo } from './schema/StockLevel'
import { StockTurnOverInfo } from './schema/StockTurnOver'
import { UnitOfMeasureInfo } from './schema/UnitOfMeasure'
import { WarehouseInfo } from './schema/Warehouse'

/**
 * An object as returned by TOTVS' EAI API.
 */
export const Object = t.union([
    CostCenterInfo,
    ItemInfo,
    UnitOfMeasureInfo,
    WarehouseInfo,
    SellerInfo,
    StockLevelInfo,
    StockTurnOverInfo
])

/**
 * A converter interface, meant to convert between TOTVS' models and ours.
 */
export interface Converter<From, To> {
    /**
     * Convert a TOTVS' EAI message to an internal model of our own.
     *
     * @param from Original message
     */
    fromInventoryUM(from: From): To

    /**
     * Converts a message in our internal odel to TOTVS' EAI's.
     *
     * @param from Original message
     */
    toInventoryUM(from: To): From
}

// Re-export types autogenerated from TOTVS' schemas!
export {
    CostCenterInfo,
    ItemInfo,
    UnitOfMeasureInfo,
    WarehouseInfo,
    SellerInfo,
    StockLevelInfo,
    StockTurnOverInfo
}